### ISSUE TITLE
Error when initializing project

### ISSUE THREAD

**Issue by DrSensor** [quasarframework/quasar-template-pwa#4]
`quasar init pwa test-pwa`

```
 ℹ Generating Quasar App...

 ✔ Downloaded App template @quasarframework/quasar-template-pwa
fs.js:954
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/tmp/quasar-template-h4btpjt/template'
    at Object.fs.statSync (fs.js:954:11)
    at Object.statSync (/usr/lib/node_modules/quasar-cli/node_modules/graceful-fs/polyfills.js:297:22)
    at Object.copySync (/usr/lib/node_modules/quasar-cli/node_modules/fs-extra/lib/copy-sync/copy-sync.js:27:84)
    at Object.copy (/usr/lib/node_modules/quasar-cli/lib/qfs.js:34:14)
    at generate (/usr/lib/node_modules/quasar-cli/bin/quasar-init:96:11)
    at /usr/lib/node_modules/quasar-cli/bin/quasar-init:90:7
    at /usr/lib/node_modules/quasar-cli/node_modules/download-git-repo/index.js:43:22
    at /usr/lib/node_modules/quasar-cli/node_modules/download/index.js:165:3
    at callback (/usr/lib/node_modules/quasar-cli/node_modules/each-async/index.js:38:4)
    at onetime (/usr/lib/node_modules/quasar-cli/node_modules/onetime/index.js:22:12)

```

**Comment by rstoenescu** [comment]
**Remember this is incomplete work**. Made it work with Quasar CLI now.
